<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="SVRAMAN-IN" failures="2" tests="2" name="Default test(failed)" time="0.095" errors="0" timestamp="19 Apr 2020 23:37:19 GMT">
  <testcase classname="demo.TestNgRetryFailedDemo" name="test3" time="0.021">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at demo.TestNgRetryFailedDemo.test3(TestNgRetryFailedDemo.java:21)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="demo.TestNgRetryFailedDemo" name="test2" time="0.007">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at demo.TestNgRetryFailedDemo.test2(TestNgRetryFailedDemo.java:15)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="demo.TestNgRetryFailedDemo" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
